version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432"
  backend:
    build:
      context: paper-fantasy-api
      args:
        UID: ${UID:-1001}
    volumes:
      - ./paper-fantasy-api:/usr/src/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    user: rails
  frontend:
    build:
      context: paper-fantasy-front
      args:
        UID: ${UID:-1001}
    volumes:
      - ./paper-fantasy-front:/usr/src/app
    ports:
      - "3000:3000"
    user: frontend
